### PR TITLE
Fix parameter error

### PR DESCRIPTION
**Pull request by babo**
It imports now with warnings only.

Unable to create documentation part: [Model name must be alphanumeric: Customer.Notes (placeholder)]. Ignoring.
Unable to create documentation part: [Model name must be alphanumeric: CustomerProfile.Notes (placeholder)]. Ignoring.
Unsupported model type 'IntegerProperty' in 200 response to method 'GET /accounts/{account}/safetospend'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /api/key'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /api/ratelimit'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /api/whoami'. Ignoring.
Unsupported model type 'IntegerProperty' in 200 response to method 'GET /currency/convert/{base}/{currency}/{amount}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /currency/list/{base}'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /insurance/car/{licensenumber}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /insurance/weatheralert/{latitude}/{longditude}'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /loans/apply'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /location/atm/{latitude}/{longditude}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /location/branch/details/{branchid}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /reports/transactions/{year}/{month}/{customerId}'. Ignoring.
Unsupported model type 'DecimalProperty' in 200 response to method 'GET /stocks/price/{ticker}/{timestamp}'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /vipps/customer'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /vipps/settlement/create'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /vipps/settlement/{settlementid}'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /vipps/settlement/{settlementid}/expense'. Ignoring.

### CODE REVIEW

**Comment by cloveras** [comment]
Hey, @babo! I have pushed some changes, including a "clean" API.json without Restlet extensions (hope AWS accepts is as-is).

**Comment by babo** [comment]
Your API was not imported due to errors in the Swagger file.
Unable to create model for 'Address': Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified]
Unable to create model for 'carDetails': Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified]
Unable to create model for 'carDetailsObjects': Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified]
Unable to put method 'POST' on resource at path '/insurance/car/offer/{licensenumber}': Invalid model name specified: null
Unable to put method 'GET' on resource at path '/reports/benchmarks/{year}/{month}/{customerId}/{customerIdCompare}': Invalid mapping expression specified: Validation Result: warnings : [], errors : [Parameter name should match the following regular expression: ^[a-zA-Z0-9._$-]+$]
Additionally, these warnings were found:
Unable to create documentation part: [Model name must be alphanumeric: Customer.Notes (placeholder)]. Ignoring.
Unable to create documentation part: [Model name must be alphanumeric: CustomerProfile.Notes (placeholder)]. Ignoring.
Unable to insert model 'Car' due to an unsatisfied schema reference.
Unsupported model type 'IntegerProperty' in 200 response to method 'GET /accounts/{account}/safetospend'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /api/key'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /api/ratelimit'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /api/whoami'. Ignoring.
Unsupported model type 'IntegerProperty' in 200 response to method 'GET /currency/convert/{base}/{currency}/{amount}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /currency/list/{base}'. Ignoring.
Reference to model 'carDetails' not found. Ignoring.
Invalid format for model application/json for method GET
Reference to model 'Car' not found. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /insurance/car/{licensenumber}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /insurance/weatheralert/{latitude}/{longditude}'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /loans/apply'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /location/atm/{latitude}/{longditude}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /location/branch/details/{branchid}'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /reports/transactions/{year}/{month}/{customerId}'. Ignoring.
Unsupported model type 'DecimalProperty' in 200 response to method 'GET /stocks/price/{ticker}/{timestamp}'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /vipps/customer'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /vipps/settlement/create'. Ignoring.
Unsupported model type 'StringProperty' in 200 response to method 'GET /vipps/settlement/{settlementid}'. Ignoring.
Unsupported model type 'ArrayModel' in request schema for 'POST /vipps/settlement/{settlementid}/expense'. Ignoring.

**Comment by cloveras** [comment]
Whups! Added "Application/JSON" all over the place, emoved everything related to Vipps, and fixed a few other things. Hope it's better this time.

**Comment by babo** [comment]
Sorry, I forgot to paste the errors here. These are still there:

Your API was not imported due to errors in the Swagger file.
Unable to create model for 'carDetails': Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified]
Unable to create model for 'Address': Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified]
Unable to put method 'GET' on resource at path '/reports/benchmarks/{year}/{month}/{customerId}/{customerIdCompare}': Invalid mapping expression specified: Validation Result: warnings : [], errors : [Parameter name should match the following regular expression: ^[a-zA-Z0-9._$-]+$]

**Comment by cloveras** [comment]
Ugh. I have made some more changes and simplifications. No errors or warnings on http://editor.swagger.io with the current version. Hope it works!

**Pull request merged**
